server:
  port: 10003

spring:
  datasource:                  # 数据源的相关配置
    #  拆分独立数据源独立database instance，或者独立scheme
#    url: jdbc:mysql://localhost:3306/foodie-cloud-item?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 12345678
  redis:
    database: 0
    host: 127.0.0.1
    password:
    port: 6379

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
