server:
  port: 8088

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
#    username: root
    password: 123456
  redis:
    # Redis 单机模式
#    database: 1
#    host: localhost
#    password:
#    port: 6379
#    # Redis 哨兵模式
#    database: 1
#    host: localhost
#    password: laona
#    port: 6379
#    sentinel:
#      master: laona-master
#      nodes: 127.0.0.1:26379, 127.0.0.1:26381, 127.0.0.1:26381
      # Redis 集群模式
    host: localhost
    password: laona
    cluster:
      nodes:
        - 127.0.0.1:6390, 127.0.0.1:6391, 127.0.0.1:6392, 127.0.0.1:6393, 127.0.0.1:6394, 127.0.0.1:6395

mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
